language: objective-c
osx_image: xcode10.2

branches:
    only:
    - master

script:
  - set -o pipefail && xcodebuild test -project Macaw.xcodeproj -scheme 'MacawOSX' ONLY_ACTIVE_ARCH=NO | xcpretty;


notifications:
    slack: exyte:kdo9FNtTOFMuMqAyyvZPDAD7
